name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Create Work Dir(FL)
      run: mkdir formatter_lib/build

    - name: Create Work Dir(FEL)
      run: mkdir formatter_ex_lib/build
      
    - name: Create Work Dir(HW)
      run: mkdir hello_world_application/build
      
    - name: Create Work Dir(SL)
      run: mkdir solver_lib/build
      
    - name: Create Work Dir(SA)
      run: mkdir solver_application/build
      
    - name: Configure CMake Formatter Lib
      working-directory: formatter_lib/build
      run: cmake ..
      
    - name: Configure CMake Formatter Extended Lib
      working-directory: formatter_ex_lib/build
      run: cmake ..
      
    - name: Configure CMake Hello World App
      working-directory: hello_world_application/build
      run: cmake ..
      
    - name: Configure CMake Solver Lib
      working-directory: solver_lib/build
      run: cmake ..
      
    - name: Configure CMake Solver App
      working-directory: solver_application/build
      run: cmake ..

    - name: Build Formatter Lib
      working-directory: formatter_lib/build
      run: make
      
    - name: Build Formatter Extended Lib
      working-directory: formatter_ex_lib/build
      run: make
      
    - name: Build Hello World Application
      working-directory: hello_world_application/build
      run: make

    - name: Build Solver Lib
      working-directory: solver_lib/build
      run: make
      
    - name: Build Solver Application
      working-directory: solver_application/build
      run: make
